import React from 'react';
import { format } from 'date-fns';
import { Bill } from '../types';

interface ReceiptProps {
  bill: Bill;
  className?: string;
}

const Receipt: React.FC<ReceiptProps> = ({ bill, className = '' }) => {
  return (
    <div id="receipt-content" className={`bg-white p-8 ${className}`}>
      <div className="text-center border-b-2 border-gray-300 pb-4 mb-6">
        <h1 className="text-3xl font-bold text-gray-800 mb-2">{bill.shopDetails.name}</h1>
        <p className="text-gray-600 mb-1">{bill.shopDetails.location}</p>
        {bill.shopDetails.phone && <p className="text-gray-600 mb-1">Phone: {bill.shopDetails.phone}</p>}
        {bill.shopDetails.email && <p className="text-gray-600">Email: {bill.shopDetails.email}</p>}
      </div>
      
      <div className="flex justify-between mb-6">
        <div>
          <p className="text-sm text-gray-600">Bill Number:</p>
          <p className="font-bold text-lg">{bill.billNumber}</p>
        </div>
        <div className="text-right">
          <p className="text-sm text-gray-600">Date:</p>
          <p className="font-bold text-lg">{format(new Date(bill.date), 'dd/MM/yyyy HH:mm')}</p>
        </div>
      </div>
      
      <table className="w-full mb-6 border-collapse">
        <thead>
          <tr className="border-b-2 border-gray-300">
            <th className="text-left py-2 px-2">Item</th>
            <th className="text-right py-2 px-2">Price</th>
            <th className="text-center py-2 px-2">Qty</th>
            <th className="text-right py-2 px-2">GST%</th>
            <th className="text-right py-2 px-2">GST Amt</th>
            <th className="text-right py-2 px-2">Total</th>
          </tr>
        </thead>
        <tbody>
          {bill.products.map((product) => {
            const subtotal = product.price * product.quantity;
            const gstAmount = (subtotal * product.gst) / 100;
            const total = subtotal + gstAmount;
            
            return (
              <tr key={product.id} className="border-b border-gray-200">
                <td className="py-3 px-2">{product.name}</td>
                <td className="text-right py-3 px-2">₹{product.price.toFixed(2)}</td>
                <td className="text-center py-3 px-2">{product.quantity}</td>
                <td className="text-right py-3 px-2">{product.gst}%</td>
                <td className="text-right py-3 px-2">₹{gstAmount.toFixed(2)}</td>
                <td className="text-right py-3 px-2 font-semibold">₹{total.toFixed(2)}</td>
              </tr>
            );
          })}
        </tbody>
      </table>
      
      <div className="border-t-2 border-gray-300 pt-4">
        <div className="flex justify-between mb-2">
          <span className="text-lg">Subtotal:</span>
          <span className="text-lg font-semibold">₹{bill.subtotal.toFixed(2)}</span>
        </div>
        <div className="flex justify-between mb-2">
          <span className="text-lg">Total GST:</span>
          <span className="text-lg font-semibold">₹{bill.totalGST.toFixed(2)}</span>
        </div>
        <div className="flex justify-between border-t border-gray-300 pt-2">
          <span className="text-xl font-bold">Total Amount:</span>
          <span className="text-xl font-bold">₹{bill.totalAmount.toFixed(2)}</span>
        </div>
      </div>
      
      <div className="text-center mt-8 pt-4 border-t border-gray-300">
        <p className="text-sm text-gray-600">Thank you for your business!</p>
        <p className="text-xs text-gray-500 mt-2">Generated by Online Bill Generator</p>
      </div>
    </div>
  );
};

export default Receipt;